- hosts: all
  tasks:
  - name: Update all packages
    sudo: yes
    dnf: name=* state=latest
    when: ansible_distribution == 'Fedora'

  - name: Install standard fedora packages
    sudo: yes
    dnf: name={{ item }} state=latest
    when: ansible_distribution == 'Fedora'
    with_items:
      - zsh
      - git
      - vim
      - xclip
      - ack

  - name: Install 'Development tools' package group
    sudo: yes
    dnf: name="@development tools" state=present
    when: ansible_distribution == 'Fedora'

  - name: Install dotfiles
    sudo: no
    git:
      repo: ssh://git@github.com/pchickey/dotfiles.git
      accept_hostkey: yes
      dest: ~/.dotfiles

  - include: tasks/tmux.yml

  - name: Install zsh config
    sudo: no
    tags: dotfiles
    git:
      repo: ssh://git@github.com/pchickey/zsh-config.git
      accept_hostkey: yes
      dest: ~/.zsh

  - name: Change shell to zsh
    sudo: yes
    command: "chsh {{ ansible_user_id }} -s /bin/zsh"

  - name: Create .zshrc symlink
    sudo: no
    tags: dotfiles
    command: ln -s ~/.zsh/zshrc ~/.zshrc
             creates=~/.zshrc

  - name: Install vim config
    sudo: no
    tags: dotfiles
    git:
      repo: ssh://git@github.com/pchickey/vim-config.git
      accept_hostkey: yes
      dest: ~/.vim

  - name: Bootstrap vim config
    sudo: no
    tags: dotfiles
    command: ./boot.sh chdir=~/.vim

  - name: Create .ackrc symlink
    sudo: no
    tags: dotfiles
    command: ln -s ~/.dotfiles/ackrc ~/.ackrc
             creates=~/.ackrc

