- name: Install tmux-2.1 dependencies
  sudo: yes
  dnf: name={{ item }} state=present
  when: ansible_distribution == 'Fedora'
  with_items:
    - gcc
    - libevent-devel
    - ncurses-devel

- name: Run tmux-2.1 installer script
  sudo: yes
  script: ./install_tmux_2.1.sh

- name: Create .tmux.conf symlink
  sudo: no
  tags: dotfiles
  command: ln -s ~/.dotfiles/tmux.conf ~/.tmux.conf
           creates=~/.tmux.conf
