- name: Update all packages
  sudo: yes
  dnf: name=* state=latest
  when: ansible_distribution == 'Fedora'

- name: Install zsh
  sudo: yes
  dnf: name=zsh state=latest
  when: ansible_distribution == 'Fedora'
  notify: Change shell to zsh

- name: Install git
  sudo: yes
  dnf: name=git state=latest
  when: ansible_distribution == 'Fedora'

- name: Install vim
  sudo: yes
  dnf: name=vim state=latest
  when: ansible_distribution == 'Fedora'

- name: Install tmux
  sudo: yes
  dnf: name=tmux state=latest
  when: ansible_distribution == 'Fedora'

- name: Install xclip
  sudo: yes
  dnf:  name=xclip state=latest
  when: ansible_distribution == 'Fedora'

- name: Install ack
  sudo: yes
  dnf:  name=ack state=latest
  when: ansible_distribution == 'Fedora'

- name: Update zsh config
  sudo: no
  tags: dotfiles
  git:  repo=ssh://git@github.com/pchickey/zsh-config.git
        accept_hostkey=yes
        dest=~/.zsh
  notify: Create .zshrc symlink

- name: Update vim config
  sudo: no
  tags: dotfiles
  git:  repo=ssh://git@github.com/pchickey/vim-config.git
        accept_hostkey=yes
        dest=~/.vim
  notify: Update vim plugins

- name: Update dotfiles
  sudo: no
  git:  repo=ssh://git@github.com/pchickey/dotfiles.git
        accept_hostkey=yes
        dest=~/.dotfiles
  notify: Create .tmux.conf symlink
  notify: Create .ackrc symlink
